services:
  backend:
      container_name: backend
      build:
        context: ./backend
      ports:
        - "5000:5000"
      env_file:
        - ./backend/.env
      depends_on:
        mysql:
          condition: service_healthy
      restart: always

  frontend:
      container_name: frontend
      build:
        context: ./frontend
      ports:
        - "4173:4173" 
     
      restart: always
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./backend/resources:/var/lib/mysql-files
      - ./backend/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always 

volumes:
  db_data:
